import type { Metadata } from "next";
import { Assistant } from "next/font/google";
import { GenericNavbar } from "@/components/general/navbar";

const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["hebrew"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Mental Wellness Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      dir="rtl"
      className={`${assistant.variable} ${assistant.className} antialiased`}
      style={{ colorScheme: "light" }}
    >
      <GenericNavbar />
      {children}
    </div>
  );
}
